### ISSUE TITLE
Unable to load on Windows

### ISSUE THREAD

**Issue by MCSZ** [open-physiology/open-physiology-viewer#56] opened 2020-09-16 20:32 UTC
```
Uncaught TypeError: Cannot read property 'numLevels' of undefined
    at Module../model/logger.js (logger.js:80)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Module../model/utils.js (index.js:387540)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Module../model/resourceModel.js (index.js:385718)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Module../model/groupTemplateModel.js (index.js:385238)
```

**Comment by albatros13** [comment] 2020-09-21 13:46
Regression bug caused by cyclic deoendency between utils.js and logger.js. Fixed by removing the use of logger from schema-based generation.

**Closed by albatros13** 2020-09-21 13:46 UTC
