### ISSUE TITLE
add json -> excel to apinatomy converter script

### ISSUE THREAD

**Issue by tgbugs** [open-physiology/open-physiology-viewer#124] opened 2021-11-16 21:19 UTC
need this for automated pipelines and to update the google sheets automatically

**Comment by albatros13** [comment] 2022-03-02 11:52
The issue is tracked via https://github.com/MetaCell/open-physiology-viewer/issues/79, hence closing the duplicate

**Closed by albatros13** 2022-03-02 11:52 UTC
